/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABadge: typeof import('antdv-next')['Badge']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    ASpace: typeof import('antdv-next')['Space']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ExceptionBase: typeof import('./components/exception/exception-base.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AAvatar: typeof import('antdv-next')['Avatar']
  const ABadge: typeof import('antdv-next')['Badge']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADescriptions: typeof import('antdv-next')['Descriptions']
  const ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
  const ADivider: typeof import('antdv-next')['Divider']
  const ADrawer: typeof import('antdv-next')['Drawer']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputPassword: typeof import('antdv-next')['InputPassword']
  const ALayout: typeof import('antdv-next')['Layout']
  const ALayoutContent: typeof import('antdv-next')['LayoutContent']
  const ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
  const ALayoutSider: typeof import('antdv-next')['LayoutSider']
  const AMenu: typeof import('antdv-next')['Menu']
  const ASpace: typeof import('antdv-next')['Space']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const ExceptionBase: typeof import('./components/exception/exception-base.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}